### PR TITLE
Improvement_make_db_table_configuration

### PR DESCRIPTION
**Pull request by ioigoume**
Make vom_members table configuration

### CODE REVIEW

**Review by NicolasLiampotis — CHANGES_REQUESTED** [review]
Default table name: voms_members

**Review by NicolasLiampotis — CHANGES_REQUESTED** [review]
It would be safer to make the name of the temp table either configurable or dynamic based on the voms table name, e.g. `${voms_tbl}_temp`

**Comment by ioigoume** [comment]
> It would be safer to make the name of the temp table either configurable or dynamic based on the voms table name, e.g. `${voms_tbl}_temp`

Done

**Review by NicolasLiampotis — APPROVED** [review]
LGTM

**Pull request merged**
